<a href="https://colab.research.google.com/github/Himanshukhanduri20/Deep-Learning-Pytorch-/blob/main/Basics_of_Pytorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators.

In [ ]:
import torch
import numpy as np

**Initializing a Tensor**

Tensors can be initialized in various ways.

Tensors can be created **directly from data.**


In [ ]:
data=[1,2,4,5,6,7]
torch.tensor(data)

tensor([1, 2, 4, 5, 6, 7])

**From a NumPy array**

In [ ]:
data=np.array(data)
data=torch.tensor(data)
print(data)
data=np.ones((2,4))
data=torch.tensor(data)
print(data)

tensor([1, 2, 4, 5, 6, 7])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


**From another tensor**

In [ ]:
x=[9,8,7,5,4,3,2]
x=torch.tensor(x)
y=torch.ones_like(x)
print(x)
print(y)
y=torch.zeros_like(y)
print(y)

tensor([9, 8, 7, 5, 4, 3, 2])
tensor([1, 1, 1, 1, 1, 1, 1])
tensor([0, 0, 0, 0, 0, 0, 0])


**With random or constant values**

In [ ]:
x=torch.ones((2,7))
print(x)
y=torch.zeros((3,6))
print(y)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


**Attributes of a Tensor**

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [ ]:
data=torch.rand((3,6))
print(f"shape :- {data.shape}")
print(f"data type :- {data.dtype}")
print(f"device :- {data.device}")

shape :- torch.Size([3, 6])
data type :- torch.float32
device :- cpu


**Operations on Tensors**

*By default, tensors are created on the CPU*. 

We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

**Standard numpy-like indexing and slicing:**

In [ ]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print(tensor)
print(tensor[:,2])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension.**

In [ ]:
data=torch.zeros((2,2))
data2=torch.ones((2,2))
data3=torch.cat([data,data2])
print(data3)
data3=torch.cat([data,data2],dim=1)
print(data3)

tensor([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.]])


**Arithmetic operations**

In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
tensor =torch.rand((3,4))
print(f"tensor :-- {tensor}")
print(f"transpose of tensor :--{tensor.T}")  #transpose of tensor

y1 = tensor @ tensor.T

y2 = tensor.matmul(tensor.T)


y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.5185, 0.4427, 0.2492, 0.5968],
        [0.4068, 0.0426, 0.4855, 0.6698],
        [0.8519, 0.8623, 0.9003, 0.2079]])
tensor([[0.5185, 0.4068, 0.8519],
        [0.4427, 0.0426, 0.8623],
        [0.2492, 0.4855, 0.9003],
        [0.5968, 0.6698, 0.2079]])


tensor([[0.2689, 0.1960, 0.0621, 0.3562],
        [0.1655, 0.0018, 0.2357, 0.4486],
        [0.7258, 0.7435, 0.8105, 0.0432]])

Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [ ]:
tensor =torch.tensor([1,2,3,4,5])
tensor1=torch.rand((2,4))
agg = tensor.sum()
agg1=tensor1.sum()
print(f"agg :- {agg}")
print(f"agg1 :- {agg1}")
agg_item = agg.item()
agg1_item = agg1.item()
print(f"agg_item :-{agg_item}, {type(agg_item)}")
print(f"agg1_item :-{agg1_item}, {type(agg1_item)}")

agg :- 15
agg1 :- 3.824166774749756
agg_item :-15, <class 'int'>
agg1_item :-3.824166774749756, <class 'float'>


**In-place operations** 

Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

In [ ]:
tensor=torch.ones((2,5))
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]])


**Bridge with NumPy**

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [ ]:
t=torch.ones(7)
print(t)
t.add_(1)
n=t.numpy()
print(f"t: {t}")
print(f"n: {n}")
t=t+10
print(t)
print(n)
t.sub_(5)
print("\n")
print(t)
print(n)

tensor([1., 1., 1., 1., 1., 1., 1.])
t: tensor([2., 2., 2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2. 2. 2.]
tensor([12., 12., 12., 12., 12., 12., 12.])
[2. 2. 2. 2. 2. 2. 2.]


tensor([7., 7., 7., 7., 7., 7., 7.])
[2. 2. 2. 2. 2. 2. 2.]
